name: Prisma Migrate PostgreSQL DB - return-articles

on:
  push:
    branches:
      - master
    paths:
      - "./prisma/**/*.*"
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: npm
      
      - name: Install dependencies
        run: npm i
      
      - name: Deploy migratons
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
